name: Lint

on:
  push:

jobs:
  build:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Lint
        uses: docker://github/super-linter
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
